version: '3.7'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"  # Ánh xạ cổng MongoDB
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin  # Tên người dùng root cho MongoDB
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword  # Mật khẩu root cho MongoDB
    volumes:
      - mongo_data:/data/db  # Lưu trữ dữ liệu MongoDB
    networks:
      - mongo_network  # Kết nối MongoDB với mạng mongo_network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo  # Kết nối với MongoDB
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin  # Tên người dùng quản trị
      - ME_CONFIG_MONGODB_ADMINPASSWORD=adminpassword  # Mật khẩu người dùng quản trị
    ports:
      - "8081:8081"  # Ánh xạ cổng Mongo Express
    depends_on:
      - mongo  # Đảm bảo mongo-express chỉ chạy khi MongoDB đã khởi động
    networks:
      - mongo_network  # Kết nối Mongo Express với mạng mongo_network

volumes:
  mongo_data:  # Định nghĩa volume để lưu trữ dữ liệu MongoDB

networks:
  mongo_network:  # Định nghĩa mạng mongo_network cho MongoDB và Mongo Express
    driver: bridge  # Sử dụng mạng bridge
