version: '3'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - product-service
      - order-service
      - customer-service
    networks:
      - microservices-network

  product-service:
    build: ./product-service
    ports:
      - "5001:5001"
    environment:
      - MONGODB_URI=mongodb+srv://teophan370:teophan370@cluster0.2fs8aqv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - microservices-network

  order-service:
    build: ./order-service
    ports:
      - "5002:5002"
    environment:
      - MONGODB_URI=mongodb+srv://teophan370:teophan370@cluster0.2fs8aqv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - microservices-network

  customer-service:
    build: ./customer-service
    ports:
      - "5003:5003"
    environment:
      - MONGODB_URI=mongodb+srv://teophan370:teophan370@cluster0.2fs8aqv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
