version: '3.8'

services:
  flask1:
    build: ./app
    container_name: flask1
    networks:
      - webnet

  flask2:
    build: ./app
    container_name: flask2
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx_lb
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - flask1
      - flask2
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
