version: '3.7'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "80:80"
    networks:
      - react-network

networks:
  react-network:
    driver: bridge
